version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: rp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - basic-tier


networks:
  basic-tier:
    driver: bridge
