management:
  endpoints:
    web:
      enabled: true
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT}

spring:
  jackson:
    time-zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
  application:
    name: XFactor Mailer Outbound Adapter
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
      secret: <redacted>
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
